# This is a config for E2B sandbox template.
# You can use template ID (yicssddcqcznreotzvxr) or template name (talk2build-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("talk2build-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("talk2build-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('talk2build-nextjs-test-2')

team_id = "fe337c16-3afe-4ace-9d47-5872040b2056"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "talk2build-nextjs-test-2"
template_id = "yicssddcqcznreotzvxr"
